Auto-DL/Auto-DL

LICENSE
requirements.txt

[Fixes #7] Add requirements file

---

BackEndApp/v1/views.py

Fixes #11
Assumes current output dir and 'test.py'

Adds path for generated file

---

BackEndApp/train.sh
BackEndApp/v1/urls.py
BackEndApp/v1/views.py

[Fixes #13 ] train route added

---

BackEndApp/BackEndApp/settings.py
BackEndApp/v1/urls.py
BackEndApp/v1/views.py

fixes #22 
This route calls the test_model module from DLMML and returns the status of whether the model compiles successfully from the provided JSON.

[Fixes #22] Adds compile route

---

requirements.txt

[Fixes #21] Memory leak was fixed in Tensorflow version 2.3.1

---

README.md

fixes #25 
Removed "chat on gitter" badge from Readme, pretty sure this is how you wanted it, tell me if you want it differently and I can change it.

 [Fixes #25] Update README.md

---

README.md

[Fixes 28] Adds slack space badge

---

README.md

fixes #42 
Note - link expires in 29 days

[Fixes #42] Updates slack link in readme

---

README.md

Suggest if you want any change to be reverted.
Also wanted to remove the Contributing section, but hopefully won't come to that.

Vocab and Punctuational Changes.

---

BackEndApp/BackEndApp/settings.py
BackEndApp/BackEndApp/urls.py
BackEndApp/authv1/admin.py
BackEndApp/authv1/apps.py
BackEndApp/authv1/connector.py
BackEndApp/authv1/models.py
BackEndApp/authv1/tests.py
BackEndApp/authv1/urls.py
BackEndApp/authv1/views.py

fixes #51 
see #31  and  see #32 
Doesn't really fix 31, 32 as proper "auth" is not yet implemented 

[Fixes #51] Add app for authentication

---

requirements.txt

[Fixes #55] Add to requirements new libraries

---

BackEndApp/authv1/views.py

[Fixes #56] Update status response in json

---

BackEndApp/authv1/auth.py
BackEndApp/authv1/models.py
BackEndApp/authv1/views.py

[Fixes #31] Create Token and Session classes

---

BackEndApp/authv1/store.py
BackEndApp/authv1/views.py

[Fixes #61] Add store class, create directory on register

---

BackEndApp/authv1/models.py
BackEndApp/authv1/urls.py
BackEndApp/authv1/views.py

[Fixes #33] Adds logout route

---

BackEndApp/authv1/store.py
BackEndApp/v1/urls.py
BackEndApp/v1/views.py

fixes #70
fixes #71
fixes #72 
fixes #73

[Fixes #70-73] Add Home Page Backend Routes

---

README.md

fixes #68 
Hey, I am pretty new to contribution so any tip will be appreciated!

[Fixed #68] Fix requirement in readme

---

BackEndApp/authv1/auth.py
BackEndApp/authv1/decorators.py
BackEndApp/authv1/models.py
BackEndApp/authv1/views.py
BackEndApp/v1/views.py

fixes #78 
Tested the decorator on 'v1/generate/' route

[Fixes #78] Adds is_authenticated decorator

---

BackEndApp/v1/urls.py
BackEndApp/v1/utils.py
BackEndApp/v1/views.py

fixes #74 
Adds a backend route to create new projects

[Fixes #74] Add create project route

---

FrontEndApp/v1-react/src/App.js
FrontEndApp/v1-react/src/Components/Login/LoginForm.js
FrontEndApp/v1-react/src/Components/Login/LoginIndex.js
FrontEndApp/v1-react/src/Components/MainApp/Homeindex.js

fixes #85 
Removed all unused imports lying around in the ReactJS files.

[Fixes #85] Compiler warnings

---

README.md

fixes #84 
Fixes the path in readme file for the React app, so that newer contributors find it easy to contribute.

[Fixes #84] Fixes the path in readme

---

BackEndApp/authv1/views.py

[Fixes #88] Fix register bug

---

FrontEndApp/v1-react/src/Components/MainApp/Step3.js

fixes #94   
Encloses the text in the file in `<p>` tag. Thus helping the linter to compile the file.

Enclosed in tags

---

BackEndApp/v1/urls.py
BackEndApp/v1/views.py

[Fixes #98] Add step 2 routes

---

BackEndApp/v1/views.py

fixes #100
Update generate to support v1 API call

[Fixes #100] Update generate as per API doc

---

BackEndApp/v1/views.py
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

[Fixes #108] Update generate route and send layers while autosaving

---

BackEndApp/train.bat
BackEndApp/train.sh
BackEndApp/v1/views.py

fixes #102
Checks the os of the user and runs the bash file or batch file accordingly. 
Note - Currently both scripts work with test.py and need to be made dynamic

[Fixes #102] Adds training for windows

---

FrontEndApp/v1-react/src/Components/MainApp/Homeindex.js
FrontEndApp/v1-react/src/Components/MainApp/Layout.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

[Fixes #110]froentend bugs

---

README.md

fixes #112
link will expire on 6th March

[Fixes #112] Updates slack link

---

FrontEndApp/v1-react/src/Components/MainApp/Layout.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

fixes #114  some bugs related to validation and learning rate

[Fixes #114] some bugs before review

---

BackEndApp/v1/utils.py
BackEndApp/v1/views.py

fixes #117   
Except "preprocessing" everything else is now dynamic

[Fixes #117] Fix harcoded params in generate view

---

BackEndApp/v1/urls.py
BackEndApp/v1/views.py

fixes #119 
Added routes "/preprocessing/save/" and "/preprocessing/get/"

[Fixes #119] Add routes to accept pre-processing params

---

README.md

fixes #123 
Updates slack link which will work for another month
Signed-off-by: Tanvi Shinde tanvi.shinde46@gmail.com

[Fixes #123] Updates slack link

---

FrontEndApp/v1-react/public/index.html
FrontEndApp/v1-react/public/manifest.json
FrontEndApp/v1-react/src/Components/MainApp/HomeService.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

[Fixes #125] Preprocessing done

---

install.sh

fixes #121   
Basic install.sh based upon the setup instructions as mentioned in the [Auto-DL docs](https://readthedocs.org/projects/auto-dl/).
Checklist:
Signed-off-by: Rahul Tejwani - <rahul.tejwani1309@gmail.com>

[Fixes #121] Add Installation Script 

---

FrontEndApp/README.md
FrontEndApp/v1-react/src/Components/Login/LoginForm.js
FrontEndApp/v1-react/src/Components/MainApp/Layout.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

[Fixes #116 & #131] Changes done

---

FrontEndApp/README.md
FrontEndApp/v1-react/src/App.js
FrontEndApp/v1-react/src/Components/Login/LoginForm.js
FrontEndApp/v1-react/src/Components/MainApp/Homeindex.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

[Fixes #135] Basic bugs

---

BackEndApp/v1/models.py
BackEndApp/v1/views.py

[Fixes #138] Adds ir to mongodb

---

BackEndApp/v1/urls.py
BackEndApp/v1/utils.py
BackEndApp/v1/views.py
FrontEndApp/v1-react/package.json
FrontEndApp/v1-react/public/manifest.json
FrontEndApp/v1-react/src/Components/MainApp/HomeService.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

fixes #149
* Add a download button to download the generated code.
* Uses `/code/download` endpoint

[Fixes #149] Add download button

---

README.md

fixes #148
Updates slack link with no expiry date

[Fixes #148] Updates slack invite link in readme

---

BackEndApp/v1/urls.py
BackEndApp/v1/views.py

fixes #153 
Add hyperparameter backend support

[Fixes #153] Add save hyperparams backend support

---

BackEndApp/v1/views.py
FrontEndApp/v1-react/public/manifest.json
FrontEndApp/v1-react/src/Components/MainApp/HomeService.js
FrontEndApp/v1-react/src/Components/MainApp/Homeindex.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

fixes #144 #143 
Hyperparams calls done and fixed some UI bugs.
PyTorch some part remaining.

[Fixes #144 #143] Hyper done and some ui bugs fixed

---

BackEndApp/v1/views.py
docs/source/installing.md

fixes #176 
fixes #152 
Updates docs --> Installation and `.env` parts
Fixes minor bug --> Old to new DLMML structure

[Fixes #152, #176] Update docs and fix DLMML bug

---

docs/source/installing.md

fixes #183 
The patch changes `python manage.py server` to `python manage.py runserver`
Signed-off-by: Steven Kolawole <45284829+SteveKola@users.noreply.github.com>

[Fixes #183] fix typo in installing.md

---

.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

fixes #186 and fixes #187
Create CODE_OF_CONDUCT.md enlisting all the rules and guidelines to be following while interacting in the community

[Fixes #186 and #187] Add CODE_OF_CONDUCT.md and CONTRIBUTING.md

---

BackEndApp/v1/views.py

fixes #182  
Hardcoded error messages

[Fixes #182]Change error message

---

BackEndApp/authv1/views.py

fixes  #164 and fixes #196  
In authv1/views.py, Session(user) in the login function was being called before checking if the user is None or not which was generationg an error in the Token class in auth.py ('NoneType' object has no Attribute 'get'). Now, Session(user) is called after checking if the user is None or not which is rightly displaying error on client side ("Invalid Credentials"). 
Displays proper error messages during Authentication instead of Exception e
Signed-off-by: mahekn23 <2018.mahek.nagdev@ves.ac.in>

[Fixes #164 and #196] Proper Error Messages in Authentication

---

BackEndApp/v1/utils.py
BackEndApp/v1/views.py
requirements.txt

fixes #161   
* Added function to clean the generated parser file using black and autoflake.
Signed-off-by: Onkar302 onkarbhatlawande@gmail.com

[Fixes #161] Clean parser generated file

---

.github/workflows/codeql-analysis.yml
FrontEndApp/v1-react/src/Components/MainApp/Step2.js
FrontEndApp/v1-react/src/Components/MainApp/validation.js

fixes #166   
Added a layer level validation check in the frontend which checks whether the inserted and/or edited layer does not create any shape related issue, and if it does returns an array for further client side validation.

[Fixes #166] Model Compile Validation 

---

BackEndApp/v1/urls.py
BackEndApp/v1/views.py

fixes #209 
Create a method for getting all the users created on a local instance

[Fixes #209] Get list of users

---

.github/workflows/linting.yml
.pre-commit-config.yaml
requirements.txt

fixes #212   
Initialized default pre-commit hooks and added support for python black. Also integrated the Python black lint check workflow via GitHub actions.

[Fixes #212] Black

---

requirements.txt

fixes #214 
Updates tf version to 2.5.0

[Fixes #214] chore: bump tensorflow to 2.5.0

---

FrontEndApp/v1-react/src/Components/MainApp/Project_table.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

fixes #158 
The downloaded file now has the name as provided in the Output Filename of the project

[Fixes #158] Make the name of the downloaded file dynamic

---

FrontEndApp/v1-react/src/Components/MainApp/Step2.js

fixes #219   
Changes input_size to input_shape

[Fixes #219] fix: change input_size to input_shape for 1st layer

---

run.sh

fixes #228 
Removes submodule init

[Fixes #228] fix: remove submodule init

---

BackEndApp/BackEndApp/settings.py
BackEndApp/authv1/emails.py

fixes #235 
New file added in authv1 app (emails.py) for storing email templates
Signed-off-by: mahekn23 <2018.mahek.nagdev@ves.ac.in>

[Fixes #235] Add email templates in authv1 app

---

.github/PULL_REQUEST_TEMPLATE.md

fixes #204 
Updates the PULL_REQUEST_TEMPLATE.md to be more inclusive and informative for newcomers.

[Fixes #204] Update PULL_REQUEST_TEMPLATE.md

---

README.md
scripts/install.sh
scripts/run.sh

Fixes #230 
Add the necessary scripts required to install and run the project on a bare metal linux machine

[Fixes #230] Installation scripts

---

scripts/run.sh

[Fixes #230] change paths in run.sh

---

FrontEndApp/v1-react/src/Components/MainApp/Homeindex.js
FrontEndApp/v1-react/src/Components/MainApp/ProjectTable.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

Fixes #242
- A Project will only be cloned if a checkbox in the Clone Project Modal (Preprocessing params / Model Layers / Hyperparams) is selected.
- If no new details are entered by the user in Step 1 of the Clone Project Modal for the new project to be cloned, the previously existing values of the project will be used.
- Fixed `useState` bug in Step2.js

[Fixes #242] Conditional Clone Project

---

BackEndApp/authv1/connector.py

Fixes #190 
Fixes the Login / Register Issue created due to SSL certificate errors.

[Fixes #190] SSL certificate Issue Resolved

---

FrontEndApp/v1-react/src/Components/MainApp/ProjectTable.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js
FrontEndApp/v1-react/src/Components/MainApp/step-2/LayerTab.js
FrontEndApp/v1-react/src/Components/MainApp/step-2/styles.js

Fixes #208 
This PR  clones  a  layer along with all its properties  and  the new generated layer is independent of the parent layer from which
it is cloned  and  changes in cloned layer doesnt affect the parent layer from which it is cloned .

[Fixes #208]  Clone layers in UI 

---

BackEndApp/authv1/auth.py

Fixes #250 
Added an OTP class 

[Fixes #250] Add OTP class

---

FrontEndApp/v1-react/src/Components/Login/LoginForm.js
FrontEndApp/v1-react/src/Components/MainApp/Homeindex.js
FrontEndApp/v1-react/src/Components/MainApp/ProjectTable.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js
FrontEndApp/v1-react/src/Components/MainApp/step-2/HyperparameterTab.js
FrontEndApp/v1-react/src/Components/MainApp/step-2/LayerTab.js
FrontEndApp/v1-react/src/Components/MainApp/step-2/PreprocessingTab.js
FrontEndApp/v1-react/src/Components/MainApp/step-2/styles.js

Fixes #201
- The entered form details are checked for a blank space input and a warning is raised. 
- Also fixed a typo where the project's 'path' was checked instead of 'data_dir' during validation.

[Fixes #201] Add blank space validation

---

FrontEndApp/v1-react/src/Components/MainApp/Step2.js
FrontEndApp/v1-react/src/Components/MainApp/step-2/HyperparameterTab.js
FrontEndApp/v1-react/src/Components/MainApp/step-2/LayerTab.js
FrontEndApp/v1-react/src/Components/MainApp/step-2/PreprocessingTab.js
FrontEndApp/v1-react/src/Components/MainApp/step-2/styles.js

Fixes #253  
Infoicons are added adjacent to all textfields which display helpertexts  explaining what an input field exactly expects ,
with description available only for a specific time after clicking them.

[Fixes #253] Infoicons to all textfields 

---

FrontEndApp/v1-react/src/App.test.js
FrontEndApp/v1-react/src/Components/MainApp/ProjectTable.js
FrontEndApp/v1-react/src/Components/MainApp/__test__/ProjectTable.test.js

Fixes #259
- Implements unit tests for the ProjectTable.js component.
- The project details including the project name, language used, library used, task, description and output file name, rendered on the Dashboard (Project Table), by the data sent from the Backend API is verified (as visible to the user).
- Mock functions and mock projects have been created to isolate the testing only to the Frontend / React-side of the app (not making any axios requests to the Backend).

[Fixes #259] Test to verify correct project details on dashboard

---

BackEndApp/authv1/urls.py
BackEndApp/authv1/views.py

Fixes #35 
Three functions added in authv1/views.py-->
forgot_password - This function sends an email to the user with an otp.
verify_otp - This function verifies the received otp.
update_password - This function accepts a new password and updates it in the database.
Signed-off-by: mahekn23 2018.mahek.nagdev@ves.ac.in

[Fixes #35]  Add forgot password functionality

---

BackEndApp/BackEndApp/settings.py
BackEndApp/requirements.txt

Fixes #199 
Added a logging configuration in `settings.py` which configures the logger globally in the Django project. It includes `file` handler as well which has been set up to create rotating logs every 7 days as of now.

[Fixes #199] Add logging configuration

---

BackEndApp/sample.env
FrontEndApp/v1-react/sample.env
README.md

[Fixes #265] Add sample.env files

---

BackEndApp/authv1/auth.py
BackEndApp/requirements.txt
BackEndApp/tests/mocks.py
BackEndApp/tests/test_token.py

fixes #278
Uses pytest and pytest-mock to write unit test for the following methods of Token class
- create
- delete
- verify

[Fixes #278] feat: add token tests

---

BackEndApp/requirements.txt

Fixes #276 
- Altered `requirements.txt` to include the correct python logging package - `colorlog`.
- Created an empty `logs/app.log` in the `BackEndApp` directory to facilitate logging in the correct path.
The PR fixes the backend logging configuration setup using `colorlog`.

[Fixes #276] Logging configuration fix for local dev environment

---

.github/workflows/backend-ci.yml
.github/workflows/pytest-testing.yml
BackEndApp/v1/utils.py

Fixes #273 
Add github workflow to check python tests via pytest.
CI/CD

[Fixes #273] Workflow for pytest

---

FrontEndApp/v1-react/src/Components/MainApp/Homeindex.js
FrontEndApp/v1-react/src/Components/MainApp/__test__/Homeindex.test.js
FrontEndApp/v1-react/src/Components/MainApp/operations/CloneProject.js
FrontEndApp/v1-react/src/Components/MainApp/operations/UpsertProject.js
FrontEndApp/v1-react/src/Components/MainApp/projects/CloneProjectModal.js
FrontEndApp/v1-react/src/Components/MainApp/projects/ProjectTable.js
FrontEndApp/v1-react/src/Components/MainApp/projects/UpsertProjectModal.js
FrontEndApp/v1-react/src/Components/MainApp/projects/__test__/ProjectTable.test.js
FrontEndApp/v1-react/src/Components/MainApp/projects/__test__/UpsertProjectModal.test.js
FrontEndApp/v1-react/src/Components/MainApp/projects/styles.js
FrontEndApp/v1-react/src/mocks/resolvers/createProjectsResolver.js

Fixes #280 
- Refactored the UI (project modals - create / edit & clone) and logic (create / edit & clone operations) to facilitate simplified testing.
- Implemented tests to verify the correct rendering of the Create and Edit Project modals (and functionality of the forms within).

[Fixes #280] Test Create and Edit Project modal render

---

BackEndApp/v1/views.py

Fixes #295
Old structure did not check whether the files existed or not, before copying from them.

[Fixes #295] Fixes cloning project bug

---

BackEndApp/BackEndApp/logging.py
BackEndApp/BackEndApp/settings.py

Fixes #297
Changed how the logger gets initialized in settings

[Fixes #297] Fixes cyclic dependency in settings-logger

---

BackEndApp/requirements.txt
BackEndApp/tests/mocks.py
BackEndApp/tests/test_otp_class.py
BackEndApp/tests/utils_tests.py

[Fixes #289] Add Unit tests for OTP class in authv1 app

---

BackEndApp/requirements.txt
BackEndApp/tests/mocks.py
BackEndApp/tests/test_user.py
BackEndApp/tests/utils_tests.py

Fixes #304 
Added unit tests for User class methods in test_user.py and the utils_tests.py contains the User class instances used for testing purposes.

[Fixes #304] Add unit tests for user class in authv1 app

---

BackEndApp/authv1/views.py

Fixes #315 
I added a return on the except code block with username as None to fix  stop UnboundLocalError: local variable 'username' referenced before assignment error

[Fixes #315] Fix  local variable 'username' on authv1 views

---

BackEndApp/v1/utils.py

Fixes #330 and fixes #323
- The generated model can now be generated and downloaded on all OSs.

[Fixes #330, #323] Fix copying and downloading of the generated file

---

BackEndApp/requirements.txt
docs/requirements.txt

Fixes #178 
Added new requirements.txt in docs and removed the overlapping ones from BackendApp

[Fixes #178] Read the docs dependencies

---

.github/configurations/commitlint.config.js
.github/configurations/parser-preset.js
.github/workflows/conventional-commit-lint.yml
.github/workflows/pr-lint.yml
CONTRIBUTING.md

Fixes #335 
Added GitHub workflows to perform:
1. Conventional commit checks
2. PR title convention checks

feat: add GitHub workflows for conventional checks (#335)

---

README.md

Fixes #379 
Signed-off by: Rahul Tejwani <rahul.tejwani1309@gmail.com>

docs: update hactoberfest guideline in readme.md

---

FrontEndApp/v1-react/public/mockServiceWorker.js
FrontEndApp/v1-react/src/Components/Deployment/DeployProjectModal.js
FrontEndApp/v1-react/src/Components/Deployment/DeploymentIndex.js
FrontEndApp/v1-react/src/Components/Deployment/DeploymentService.js
FrontEndApp/v1-react/src/Components/MainApp/Homeindex.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js
FrontEndApp/v1-react/src/Components/MainApp/operations/DeleteProject.js
FrontEndApp/v1-react/src/Components/RecommendationService.js

* #293 - Cleanup Warnings
* Apply suggestions from code review
Co-authored-by: Mcvean Soans <69250084+McTechie@users.noreply.github.com>
Co-authored-by: Aditya Srivastava <39651310+ADI10HERO@users.noreply.github.com>
Co-authored-by: Mcvean Soans <69250084+McTechie@users.noreply.github.com>

fix: cleanup warnings (Partial) (#353)

---

docs/source/devguide.md

docs: Fixed a typo

---

SECURITY.md

chore: add secuirty.md

---

CONTRIBUTING.md

Fixes #396
Which corrects some typos throughout the CONTRIBUTING.md file

docs: Suggested CONTRIBUTING.md changes

---

BackEndApp/authv1/auth.py
BackEndApp/authv1/decorators.py
BackEndApp/authv1/models.py
BackEndApp/tests/test_store.py
BackEndApp/v1/urls.py
BackEndApp/v1/views.py

Removed the non-essential imports from the BackEndApp
Fixes #320 
Removed all the non-essential imports from the BackEndApp to make sure that the code is clean and concise 
<-- -If we didn't approve off or discuss your PR in Github issues or slack there's a high chance it will not be merged.
The following links the related issue to the PR (https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
-->

chore: Purged Unwanted Imports in BackEndApp

---

BackEndApp/sample.env

Fixes #393
Added bare minimum comments to guide users in `BackEndApp/sample.env`
Sample Env file present in `BackEndApp`

chore: update backend sample.env

---

FrontEndApp/autodl-platform/.env.example
FrontEndApp/v1-react/sample.env

Fixes #394 
- Added bare minimum comments to guide users in `FrontEndApp/v1-react/sample.env`
- Created `FrontEndApp/autodl-platform/.env.example`
Sample Env files present in `FrontEndApp`

chore: upsert frontend sample env files

---

scripts/run.sh

Fixes #383 
Was a simple case of bash whitespace escaping on cd command. I wrapped the variable with double quotes ( " ) to contain it.
Installation scripts (run.sh)

fix: fix whitespace escaping on run.sh

---

scripts/run.sh

fix: scripts/run.sh modified to resolve error #448

---

FrontEndApp/autodl-platform/components/AppBar/AppBar.tsx
FrontEndApp/autodl-platform/components/AuthForm/AuthForm.tsx
FrontEndApp/autodl-platform/components/Donate/Donate.tsx
FrontEndApp/autodl-platform/components/ProjectCard/ProjectCard.tsx
FrontEndApp/autodl-platform/components/SideBar/SideBar.tsx
FrontEndApp/autodl-platform/layouts/Auth.tsx
FrontEndApp/autodl-platform/layouts/Main.tsx
FrontEndApp/autodl-platform/package-lock.json
FrontEndApp/autodl-platform/package.json
FrontEndApp/autodl-platform/pages/_app.tsx
FrontEndApp/autodl-platform/pages/_document.tsx
FrontEndApp/autodl-platform/pages/home/index.tsx
FrontEndApp/autodl-platform/styles/theme.tsx
FrontEndApp/autodl-platform/utils/routes.ts

Package Version Upgrade #409
Updated version as per https://mui.com/guides/migration-v4/#theme 
Added:
"@emotion/react": "^11.5.0",
"@emotion/styled": "^11.3.0",
"@mui/icons-material": "^5.0.5",
"@mui/lab": "^5.0.0-alpha.53",
"@mui/material": "^5.0.6",
"@mui/styles": "^5.0.2",
Removed:
"@material-ui/core": "^4.12.3",
"@material-ui/icons": "^4.11.2",
"@material-ui/lab": "^4.0.0-alpha.60",
Notes:
1) Error: Cannot find module '@mui/styles/makeStyles' - installed -- So need to add @mui/styles
2) /pages/_app.tsx
13:3  Error: Definition for rule '@typescript-eslint/no-empty-interface' was not found.  @typescript-eslint/no-empty-interface
-- According to https://palantir.github.io/tslint/rules/no-use-before-declare/ page, this rule is discouraged as modern TypeScript does not use it and is slow …

feat: material-ui package upgrade to v5 (#409)

---

FrontEndApp/v1-react/package-lock.json
FrontEndApp/v1-react/src/Components/MainApp/HomeService.js
FrontEndApp/v1-react/src/Components/MainApp/Step2.js

fix: Auth bug in frontend V1

---

BackEndApp/requirements.txt

added razorpay -> requirements.txt
`requirements.txt`

fix: updated Backend python requirements

---

docs/source/installing.md

Fixes #484 
I have updated the path of FrontEndApp for installing the dependencies using `npm install` as it was wrong earlier.

docs: Updated setup instructions for FrontEndApp

---

FrontEndApp/v1-react/src/Components/MainApp/Step2.js

feat: Rendering the generated code before downloading the file

---

BackEndApp/requirements.txt
BackEndApp/v1/utils.py

Upgrade python cryptography package with pycrypto.
Fixes #356 

fix: Upgrade python cryptography package with pycrypto #356

---

scripts/run.sh

Fixes #452
This PR is related to a feature improvement in auto-dl for giving options for the installation of two front-end versions.
The motivation behind the PR is related to WOC2.0 participation.

feat: Run.sh new frontend support #452

---

FrontEndApp/autodl-platform/styles/theme.tsx

Fixes #457 
A small change in theme creation has solved the issue, no more deprecation warnings now.

fix: theme deprecation solved

---

FrontEndApp/autodl-platform/components/AuthForm/AuthForm.tsx
FrontEndApp/autodl-platform/components/SideBar/SideBar.tsx

Signed-off-by: RusherRG <rushang101@gmail.com>
Fixes #464
Update the Alert functional component to explicitly use `React.forwardRef` as mentioned [here](https://mui.com/components/snackbars/#customization)

fix(ui): MuiAlert bug related to React.forwardRef
